const MockConstants = {
  VALID_EMAIL: 'simposio@email.com',
  VALID_PASSWORD: '!senhaS3CR3T4#',
  INVALID_EMAIL_1: '@email.com',
  INVALID_EMAIL_2: 'email@.com',
  INVALID_EMAIL_3: 'emailemail.com',
  INVALID_EMAIL_4: 'email@email',
  INVALID_PASSWORD: 'é isso',
  EMAIL_TEST_ID: 'common_login__input-email',
  PASSWORD_TEST_ID: 'common_login__input-password',
  BTN_TEST_ID: 'common_login__button-login',
  LOGIN_REGISTER_BTN: 'common_login__button-register',
  REGISTER_NAME_TEST_ID: 'common_register__input-name',
  REGISTER_EMAIL_TEST_ID: 'common_register__input-email',
  REGISTER_PASSWORD_TEST_ID: 'common_register__input-password',
  REGISTER_BTN: 'common_register__button-register',
  INVALID_ERROR_REGISTER: 'common_login__element-invalid-email',
  SELLER_ORDERS_ELEMENT_ORDER_ID_TEST_ID: 'seller_orders__element-order-id-1',
  ALL_ORDERS_BTN_TEST_ID: 'customer_products__element-navbar-link-orders',
  LOGOUT_BTN_TEST_ID: 'customer_products__element-navbar-link-logout',
  INVALID_NAME: 'Sim',
  VALID_NAME: 'Tio da Silva',
};

export default MockConstants;
