version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db_delivery_app
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: delivery-app-dev
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: delivery_backend
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    # command: npm run dev
    stdin_open: true
    tty: true
    environment:
      NODE_ENV: development
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: delivery-app
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    depends_on:
      - mysql
    ports:
      - "3001:3001"

volumes:
  mysql_data:
